version: 2
jobs:
  build:
    docker:
      - image: python:3.7.2-stretch
    
    working_directory: ~/repo
    
    steps:
       - checkout
      
       - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "requirements.txt"}}
            - v1-dependencies-
              
       - run:
          name: Install Dependency
          command: |
             python -m venv venv
             . venv/bin/activate
             make install
             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 && \
                chmod +x /bin/hadolint
       - save_cache:
            paths: 
             - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt"}}
       - run:
           name: run lint
           command: |
             . venv/bin/activate
             make lint